### ISSUE TITLE
Could not include SatispayInStore

### ISSUE THREAD

**Issue by manand85** [satispay/in-store-api-swift-sdk#1]
Hi,
i've got an issue importing SatispayInStore that i cannot resolve.
Could you help me please?
<img width="1301" alt="schermata 2018-07-10 alle 10 19 22" src="https://user-images.githubusercontent.com/41051914/42501738-aab49aae-8434-11e8-9676-1f560ce02b53.png">

**Comment by manand85** [comment]
recompiling manually i got this error

/Volumes/iPraticoData/SourceTree/satispay-ipratico/Carthage/Checkouts/in-store-api-swift-sdk/SatispayInStore/Networking/Protocol/ProtocolResponseVerifier.swift:106:22: error: value of type '[String]' has no member 'compactMap'
        let toSign = headers.compactMap({ name -> String? in
                     ^~~~~~~ ~~~~~~~~~~
/Volumes/iPraticoData/SourceTree/satispay-ipratico/Carthage/Checkouts/in-store-api-swift-sdk/SatispayInStore/Models/Transaction.swift:12:15: error: type 'Transaction' does not conform to protocol 'Equatable'
public struct Transaction: Decodable, Equatable {

using xcode 9.2

**Comment by pNre** [comment]
Ciao, l'ultima versione del framework richiede l'utilizzo di Swift ≥ 4.1 che è disponibile con Xcode 9.3 e successivi.
Se hai bisogno di continuare ad usare la versione 4.0 di Swift puoi provare una delle release precedenti (la [`0.1.10`](https://github.com/satispay/in-store-api-swift-sdk/releases/tag/0.1.10) dovrebbe andare bene).

**Comment by manand85** [comment]
Ciao,
 sto usando xcode 9.4.1, con carthage allineato all'ultima versione xcode command line della 9.4.1.
Quando eseguo il carthage update mi scarica a prescindere la versione 0.1.11.
Non compilo correttamente.
Ho provato a forzare il download della 0.1.3 tramite cartfile ma la compilazione non va a buon fine.

**Comment by pNre** [comment]
Che errore di compilazione hai con Carthage?

**Comment by manand85** [comment]
[carthage-xcodebuild.oYEK71.log](https://github.com/satispay/in-store-api-swift-sdk/files/2180582/carthage-xcodebuild.oYEK71.log)

**Comment by pNre** [comment]
Lo script che builda OpenSSL non supporta gli spazi nel percorso di Xcode.
Prova a rinominare `Xcode 9.4.1.app` in `Xcode-9.4.1.app` o simili.

**Comment by manand85** [comment]
Ciao,

ho provato a togliere gli spazi dal nome dell'app ma non cambia comunque nulla. Che versione del pacchetto devo scaricare?
Grazie

**Comment by pNre** [comment]
L'ultima, 0.1.11.
Nel log di carthage hai sempre lo stesso errore?

**Comment by manand85** [comment]
no, ora mi da "Unable to determine local Swift version."
Grazie mille per la disponibilità.

Andrea

**Comment by manand85** [comment]
Ho modificato un setting, ora riprovo

**Comment by manand85** [comment]
E' riuscito a compilare con xcode 9.1.4

**Comment by pNre** [comment]
Perfetto, chiudo la issue.
